const AUTHENTICATION_BASE_URL = process.env.REACT_APP_AUTHENTICATION_BASE_URL;

const AUTHENTICATION_ENTRY_POINT = '/api';

const AUTHENTICATION_USERS_LIST = 'user.index';

const AUTHENTICATION_USER_CREATE = 'user.create';

export {
	AUTHENTICATION_BASE_URL,
	AUTHENTICATION_ENTRY_POINT,
	AUTHENTICATION_USERS_LIST,
	AUTHENTICATION_USER_CREATE,
};
